feat: agrega articulo de analisis de deuda tecnica
bukhr/tech-blog pull request #9
Opened 2023-09-15 03:03 UTC by meraioth

2023-09-15 12:43 UTC, catapim requested changes
Está súper. 
Corregí algunos nombres propios para que partan con mayúscula, agregué algunos signos de puntuación, exclamación o pregunta, y reemplacé algunas cosas para que no suenen tan repetidas.

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +En buk día a día nos enfocamos en la calidad del código que estamos escribiendo, porque entendemos que una mejor calidad de código permitirá que podamos resolver problemas a nuestros clientes de form
```suggestion
En Buk día a día nos enfocamos en la calidad del código que estamos escribiendo, porque entendemos que nos permitirá resolver problemas a nuestros clientes de forma más rápida, entregándoles nuevas features en menos tiempo.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +He aquí el dilema que muchos de ustedes han visto en distintos contextos, que un proyecto sea rápido, barato y bueno, es una utopía, siempre debemos sacrificar algo para cubrir otro.
pregunta

aquí quieres decir siempre hay que sacrificar uno de los siguientes elementos: rapidez, precio y calidad para cubrir otro?

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +En buk intuimos que nuestras features van dejando algún grado de deuda técnica, es por eso que apostamos de forma media arbitraria que el 20% del tiempo de nuestros sprints lo atacaríamos a deuda téc
```suggestion
En Buk intuimos que nuestras features van dejando algún grado de deuda técnica, es por eso que apostamos de forma media arbitraria que el 20% del tiempo de nuestros sprints lo atacaríamos a deuda técnica.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Happy problem! tenemos presupuesto para mejorar nuestro codigo! ahora el problema que nos surgió es, en que invertimos ese tiempo?.
```suggestion
Happy problem! ¡Tenemos presupuesto para mejorar nuestro codigo! Ahora el problema que nos surgió es, ¿en qué invertimos ese tiempo?.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Decidimos mirar este problema de una manera más integral que solo usar una herramienta de análisis de código estático como lo son los cops, sonarcloud, etc.
```suggestion
Decidimos mirar este problema de una manera más integral que solo usar una herramienta de análisis de código estático como lo son los cops, Sonarcloud, etc.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Creemos firmemente que los síntomas de nuestra deuda técnica vuelven en forma de errores (usamos sentry para monitoreo de errores), de problemas de usabilidad (usamos freshdesk para la gestión de inc
```suggestion
Creemos firmemente que los síntomas de nuestra deuda técnica vuelven en forma de errores (usamos Sentry para monitoreo de errores), de problemas de usabilidad (usamos Freshdesk para la gestión de incidencias), de problemas de velocidad de desarrollo (usamos Jira para la gestión de nuevos features).
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +- **Codemaat** (Adam Tornhill si estás leyendo, te queremos mucho): Análisis social de la interacción que tiene nuestro repositorio, usando la historia de nuestros commits somos capaces de obtener un
```suggestion
- **Code Maat** (Adam Tornhill si estás leyendo, te queremos mucho): Análisis social de la interacción que tiene nuestro repositorio, usando la historia de nuestros commits somos capaces de obtener un promedio móvil de la cantidad de veces que un archivo es cambiado, en teoría un archivo no debería sufrir muchos cambios a lo largo del tiempo, es un warning para nosotros si lo hace. En el repo de Code Maat existen un montón de métricas interesantes a nivel organizacional y de relaciones entre archivos y autores.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Por ultimo creamos una herramienta (algo básica) basada en el repositorio de CodeMaat para poder ver las métricas de forma más visual, en la siguiente imagen se ven nuestras subcarpetas del proyecto,
```suggestion
Por último creamos una herramienta (algo básica) basada en el repositorio de Code Maat para poder ver las métricas de forma más visual, en la siguiente imagen se ven nuestras subcarpetas del proyecto, mientras más en rojo más lineas duplicadas y mientras más grande el circulo más líneas de código.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Otra de las particularidades de buk es que tenemos un monolito grande, por lo cual usamos codeowners para saber de qué equipo es cada archivo
```suggestion
Otra de las particularidades de Buk es que tenemos un monolito grande, por lo que usamos codeowners para saber de qué equipo es cada archivo
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Tomando estos inputs decidimos crear un google collab (que dejaremos al final para que lo puedas probar), para ir revisando los resultados
```suggestion
Tomando estos inputs decidimos crear un Google Collab (que dejaremos al final para que lo puedas probar), para ir revisando los resultados
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Usamos la API de sentry para traernos los eventos, obtenemos la traza, buscamos si contiene alguno de nuestros archivos y asumimos que el error es del primer archivo que aparece, luego contamos y agr
```suggestion
Usamos la API de sentry para traernos los eventos, obtenemos la traza, buscamos si contiene alguno de nuestros archivos y asumimos que el error es del primer archivo que aparece, luego contamos y agrupamos por archivo, finalmente tenemos el total de errores por archivo.
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Lo primero que debemos hacer es descargar el registro de cambios de github, esto corriendo lo siguiente dentro de la carpeta de nuestro proyecto:
```suggestion
Lo primero que debemos hacer es descargar el registro de cambios de Github, esto corriendo lo siguiente dentro de la carpeta de nuestro proyecto:
```

2023-09-15 12:43 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +La decisión basada en datos junto al conocimiento de cada equipo, que conoce a nuestros clientes hará que podamos enfocar ese 20% de tiempo en resolver deuda técnica relevante para poder tener un may
```suggestion
La decisión basada en datos junto al conocimiento de cada equipo, que comprende a nuestros clientes hará que podamos enfocar ese 20% de tiempo en resolver deuda técnica relevante para poder tener un mayor y mejor delivery.
```

2023-09-15 13:29 UTC, meraioth commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +He aquí el dilema que muchos de ustedes han visto en distintos contextos, que un proyecto sea rápido, barato y bueno, es una utopía, siempre debemos sacrificar algo para cubrir otro.
exacto

2023-09-15 19:16 UTC, vjlira commented
Wena Mera, está buenísimo el artículo, tengo un par de comentarios/sugerencias considerando lo que vivimos en rmcl, por si quieres complementar con algo:

1. Los datos apañan mucho a tener fundamentos de que algo no está tan bueno y a medir la mejora, pero creo que igual puede ser bueno sumar al análisis algo un poco más cualitativos para tomar la mejor decisión. En particular pienso en dos: Mirar el tablero de freshdesk y revisar qué temas son los que más tickets generan (nosotros priorizamos Previred por esa razón principalmente).Y preguntarle a los mismos devs donde sienten que tienen dolores (al final ese es el objetivo de pagar la deuda).
2. Creo que también es bueno definir cómo trabajar la deuda que se va encontrando en el camino, nosotros hicimos este grafico en [miro](https://miro.com/app/board/uXjVO5nswAg=/?share_link_id=676916723553) para eso 👌 :
<img width="914" alt="image" src="https://github.com/bukhr/tech-blog/assets/26437431/d3f8455f-3fe2-449d-a8d6-9d04f648f481">

2023-09-16 01:13 UTC, meraioth commented
> * Los datos apañan mucho a tener fundamentos de que algo no está tan bueno y a medir la mejora, pero creo que igual puede ser bueno sumar al análisis algo un poco más cualitativos para tomar la mejor decisión. En particular pienso en dos: Mirar el tablero de freshdesk y revisar qué temas son los que más tickets generan (nosotros priorizamos Previred por esa razón principalmente).Y preguntarle a los mismos devs donde sienten que tienen dolores (al final ese es el objetivo de pagar la deuda).

sobre esto lo mencione al final apuntando al roadmap, pero agregare lo del freshdesk y los insights de los devs

sobre el flujo no lo agregué porq el articulo quedo extenso y la idea es no aburrir al lector

2023-09-20 16:16 UTC, catapim requested changes

2023-09-20 16:16 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +He aquí el dilema que muchos de ustedes han visto en distintos contextos, que un proyecto sea rápido, barato y bueno, es una utopía, siempre debemos sacrificar algo para cubrir otro.
```suggestion
He aquí el dilema que muchos de ustedes han visto en distintos contextos. Que un proyecto sea rápido, barato y bueno es una utopía. Siempre hay que sacrificar alguno de los anteriores, para cubrir otro.
```

2023-09-20 16:34 UTC, catapim requested changes

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Este fenómeno es bien conocido en la industria del software y usualmente lo que se sacrifica es la calidad, generando el concepto de [deuda técnica](https://www.outsystems.com/glossary/what-is-techni
```suggestion
Este fenómeno es bien conocido en la industria del software y **usualmente lo que se sacrifica es la calidad**, generando el concepto de [deuda técnica](https://www.outsystems.com/glossary/what-is-technical-debt/). Existe mucha bibliografía al respecto por lo que no ahondaré en el tema.  Lo importante de la analogía es que **como cualquier deuda, si no es pagada genera intereses y cada vez se vuelve más dificil llevarla a 0**.
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +En Buk intuimos que nuestras features van dejando algún grado de deuda técnica, es por eso que apostamos de forma media arbitraria que el 20% del tiempo de nuestros sprints lo atacaríamos a deuda téc
Entiendo que haya sido de forma arbitraria la asignación del 20%, pero suena demasiado impreciso jaja.  ¿Hay algún otro insight que puedas sumar a la razón de esa cifra?

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Decidimos mirar este problema de una manera más integral que solo usar una herramienta de análisis de código estático como lo son los cops, Sonarcloud, etc.
```suggestion
**Decidimos mirar este problema de una manera más integral que solo usar una herramienta de análisis de código estático** como lo son los Cops, SonarCloud, etc.
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Creemos firmemente que los síntomas de nuestra deuda técnica vuelven en forma de errores (usamos Sentry para monitoreo de errores), de problemas de usabilidad (usamos Freshdesk para la gestión de inc
```suggestion
Creemos firmemente que los síntomas de nuestra deuda técnica vuelven en forma de errores (usamos [Sentry](https://sentry.io) para monitoreo de errores), de problemas de usabilidad (usamos [Freshdesk](https://www.freshdeskworks.com) para la gestión de incidencias), de problemas de velocidad de desarrollo (usamos [Jira](https://www.atlassian.com/software/jira) para la gestión de nuevos features).
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +- **Sentry**: Análisis de errores de nuestra aplicación, nuestra heurística es que cada vez que tenemos un error en sentry tomamos el primer archivo de la traza del error para asignarle un contador (
```suggestion
- **Sentry**: Análisis de errores de nuestra aplicación, nuestra heurística es que cada vez que tenemos un error en Sentry tomamos el primer archivo de la traza del error para asignarle un contador (por _evento_, no por _issue_)
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +- **SonarCloud**: Análisis de código estático, ofrece un [montón de métricas](https%3A%2F%2Fdocs.sonarcloud.io%2Fdigging-deeper%2Fmetric-definitions%2F), nos enfocamos en Cognitive Complexity, Duplic
```suggestion
- **SonarCloud**: Análisis de código estático que ofrece un [montón de métricas](https%3A%2F%2Fdocs.sonarcloud.io%2Fdigging-deeper%2Fmetric-definitions%2F), nos enfocamos en b y la más obvia de todas: **Lines of code**
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +- **Test Coverage**: En nuestro pipeline de CI tenemos un job que nos entrega el test coverage de nuestra app (de momento no tenemos esa parte integrada con SonarCloud, si ya lo tienes omite este pas
```suggestion
- **Test Coverage**: En nuestro pipeline de CI tenemos un **job que nos entrega el test coverage de nuestra app** (de momento no tenemos esa parte integrada con SonarCloud y si ya lo tienes, omite este paso).
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Otra de las particularidades de Buk es que tenemos un monolito grande, por lo que usamos codeowners para saber de qué equipo es cada archivo
```suggestion
Otra de las particularidades de Buk es que tenemos un monolito grande, por lo que usamos [Codeowners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) para saber de qué equipo es cada archivo
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Tomando estos inputs decidimos crear un Google Collab (que dejaremos al final para que lo puedas probar), para ir revisando los resultados
```suggestion
Tomando estos inputs decidimos crear un **Google Colab** (que dejaremos al final para que lo puedas probar), para ir revisando los resultados
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Usamos la API de sentry para traernos los eventos, obtenemos la traza, buscamos si contiene alguno de nuestros archivos y asumimos que el error es del primer archivo que aparece, luego contamos y agr
```suggestion
Usamos la API de Sentry para traernos los eventos, obtenemos la traza, buscamos si contiene alguno de nuestros archivos y asumimos que el error es del primer archivo que aparece. Luego contamos y agrupamos por archivo, y finalmente tenemos el total de errores por cada uno de ellos.
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +### Codemaat
```suggestion
### Code Maat
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +**Intrucciones para correrlo con docker:**
```suggestion
**Intrucciones para correrlo con Docker:**
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Una vez que tenemos todas las métricas, necesitamos normalizar y ponderar para obtener un número que nos pueda resumir toda la información
```suggestion
Una vez que tenemos todas las métricas, necesitamos normalizar y ponderar para obtener un número que nos pueda resumir toda la información.
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Por último creamos una herramienta (algo básica) basada en el repositorio de Code Maat para poder ver las métricas de forma más visual, en la siguiente imagen se ven nuestras subcarpetas del proyecto
```suggestion
Por último creamos una herramienta (algo básica) basada en el repositorio de Code Maat para poder ver las métricas de forma más visual. En la siguiente imagen se ven nuestras subcarpetas del proyecto, mientras más en rojo más lineas duplicadas y mientras más grande el circulo más líneas de código.
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +Luego de obtener los datos y resumirlos al máximo, cruzamos esta información con nuestro roadmap para priorizar de mejor manera, creemos firmemente que resolver aquella deuda técnica de código que mo
```suggestion
Luego de obtener los datos y resumirlos al máximo, cruzamos esta información con nuestro roadmap para priorizar de mejor manera. Creemos firmemente que **resolver aquella deuda técnica de código que modificaremos en el corto plazo será un empujón para entregar mejores features a nuestros clientes**.
```

2023-09-20 16:34 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +[Link al Google Collab con el step by step](https://gist.github.com/meraioth/9454b2894ce5792637043063d3a440bc)
> u otros equipos donde su coverage está sobre el 80%, éstas métricas que se vuelven irrelevantes para el análisis.

Creo que esa parte no es muy clara

2023-09-22 12:23 UTC, meraioth commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +En Buk intuimos que nuestras features van dejando algún grado de deuda técnica, es por eso que apostamos de forma media arbitraria que el 20% del tiempo de nuestros sprints lo atacaríamos a deuda téc
@llekn me das una mano aca?

2023-09-22 12:25 UTC, meraioth commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +- **SonarCloud**: Análisis de código estático, ofrece un [montón de métricas](https%3A%2F%2Fdocs.sonarcloud.io%2Fdigging-deeper%2Fmetric-definitions%2F), nos enfocamos en Cognitive Complexity, Duplic
dices dejar en bold todos los conceptos? puede ser muy sobrecargado a la vista una lista de bolds

2023-10-06 14:03 UTC, catapim commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +En Buk intuimos que nuestras features van dejando algún grado de deuda técnica, es por eso que apostamos de forma media arbitraria que el 20% del tiempo de nuestros sprints lo atacaríamos a deuda téc
_En Buk intuimos que nuestras features van dejando algún grado de deuda técnica, por lo mismo, decidimos (un tanto arbitrariamente) que el 20% del tiempo de nuestros sprints, lo usaríamos para saldar esas deudas._

2023-10-11 19:31 UTC, meraioth commented on _posts/2023-09-14-análisis-integral-para-encontrar-deuda-técnica.md
> +En Buk intuimos que nuestras features van dejando algún grado de deuda técnica, es por eso que apostamos de forma media arbitraria que el 20% del tiempo de nuestros sprints lo atacaríamos a deuda téc
resuelto 😄

2023-10-11 19:35 UTC, catapim approved these changes

2023-10-11 19:37 UTC, merged